# Generated by Django 4.2.3 on 2024-09-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plato_entrada', models.CharField(blank=True, max_length=128, null=True)),
                ('plato_principal', models.CharField(blank=True, max_length=128, null=True)),
                ('employee', models.CharField(blank=True, max_length=255, null=True)),
                ('postre', models.CharField(blank=True, max_length=128, null=True)),
                ('order_datetime', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
