# Generated by Django 4.2.3 on 2024-09-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plato_entrada', models.CharField(blank=True, max_length=128, null=True)),
                ('plato_principal', models.CharField(blank=True, max_length=128, null=True)),
                ('postre', models.CharField(blank=True, max_length=128, null=True)),
                ('menu_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='employee',
            new_name='empleado',
        ),
    ]
