# Generated by Django 4.2.3 on 2024-09-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menu_rename_employee_pedido_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
