# Generated by Django 4.2.3 on 2024-09-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pedido_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
